include:
  - "db.docker-compose.yml"

services:
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/api
      - VITE_USE_MOCK_API=false

  backend:
    build: ./backend
    ports: # mapping local machine port -> container port
      - "8000:8000"
    environment: # environment variables passed into backend
      - API_ROOT_PATH=
      - DB_HOST=db      # IMPORTANT: use service name "db"
      - DB_PORT=5432
      - DB_NAME=finance
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on: # ensures database starts before the backend
      - db
